export const mouthItemList = [
    "Shame",
    "Lolipop",
    "Wild",
    "Drooling",
    "Snggletooth",
    "X",
    "Depressed",
    "Open",
    "Close",
    "Medical mask",
];

export const backgroundList = [
    "Orchid",
    "Darksea",
    "Crimsom",
    "Green",
    "Yellow",
    "Cornflower",
];

export const accessoryList = [
    "Glasses red",
    "No accessory",
    "Medal bronze",
    "Glasses heart",
    "Glasses blue",
    "Glasses pixel",
    "Monocle",
    "Goggles red",
    "Glasses yellow",
    "Medal silver",
    "Goggles blue",
    "Sunglasses",
    "Eye patch",
    "Bandage",
    "Scouter purple",
    "3d glasses",
    "Scouter khaki",
    "Medal gold",
    "Board",
    "Flushing",
];

export const clothesList = [
    "Colorfull hanbok",
    "Cardigan pink",
    "Office worker",
    "Hoodie blue",
    "Tanktop stripe",
    "Button sleeve yellow",
    "Tanktop blue",
    "Warrior",
    "Sweater rose",
    "Sweater red",
    "Sweater heart",
    "Tuxedo",
    "Dress",
    "Strap blue",
    "Hanbok",
    "Strap smile",
    "Button sleeve stripe",
    "Dress pink",
    "AP short sleeve",
    "Hoodie red",
    "Sweater purple",
    "Tanktop gang",
    "Sweater yellow",
    "Button sleeve purple",
    "Tanktop purple",
    "Cardigan leaf",
    "Hoodie purple",
    "Warrior black",
    "Nobless white",
    "Button sleeve pink",
    "Strap yellow",
    "Nobless navy",
    "Sailor suit",
    "Suit",
];

export const headList = [
    "Horn mix",
    "Milk",
    "Horn blue",
    "Smile pin",
    "Horn purple",
    "Penguin",
    "Beret red",
    "Beret green",
    "Cowboy",
    "Band red",
    "Afro black",
    "Beret navy",
    "Faint",
    "Afro dirty",
    "Visor orange",
    "Ribbon",
    "Knight",
    "Penguin egg",
    "Visor yellow",
    "Band purple",
    "Band buterfly",
    "Rice hat",
    "Crown",
    "Visor navy",
    "Tiara",
    "Visor pink",
    "Fried egg",
    "Beanie",
    "No head",
    "Chef",
    "Knight gold",
    "Eternal flame",
    "Horn red",
    "Flame",
    "Angel",
    "Butterfly pin",
    "Devil",
];

export const speciesList = [
    "Seal",
    "Dog",
    "Turtle",
    "Cat",
    "Ape",
    "Rabbit",
    "Pig",
    "Tiger",
];

export const eyeslist = [
    "Tired",
    "Dizzy",
    "Brave",
    "Tomboy",
    "Smile",
    "Odd eye",
    "Wink",
    "Cheerful",
    "Xx",
    "Heart",
    "Lazy",
    "Staring",
    "Star",
    "Happy",
];
